# -*- coding: utf-8 -*-
"""codigo_projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJwXxQ93gp4Qg_OlUs5Enm7dAymT3DQL
"""

### IMPORTS

"""Mostra os arquivos que tem no mesmo espaço que o código, é importante pra garantir que vai encontrar o arquivo que será lido"""

!pwd #mostra o local onde tem o arquivo
!ls  #lista todos os arquivos no espaço

"""**Primeiro bloco:** cria uma função genérica pra identificar o arquivo, ler o título e a sequência em si.

**Segundo bloco:** inicia o loop "for" com o condicional "if" que vai ser responsável por ler linha a linha pra entender se é parte da sequência ou se é uma nova por meio dos comandos abaixo:
- **Strip:** trata as quebras de linhas
- **Startswith:** identifica o inicio de sequência e retira o ">"
- **yield:** devolve na saída o que já foi analisado e finalizado
  essa parte: "header = linha[1:]" atualiza o nome da sequência quando a última acabou, senão adiciona as outras linhas.

Em resumo, identifica onde tem um novo nome de sequência e tudo que não é nome ele trata e junta considerando ser a sequência em si.


**Terceiro bloco:** "chama" a função que criamos e aplica para o nosso .fasta, para isso funcionar só precisamos colocar o nome do arquivo onde estava a váriavel genérica "arquivo" -> ler_fasta(arquivo)

E dicionei os "print" só para nos mostrar as informações que nossa função leu.
ps: coloquei pra mostrar parcial as sequências pra não ficar muito poluído


"""

### FUNÇÃO PARA LER .FASTA

proteina = "/content/uniprotkb_ctenitoxin_2025_11_13.fasta"

#Primeiro bloco
def ler_fasta(arquivo):
    with open(arquivo, 'r') as f:
        header = ""
        sequencia = ""

#Segundo bloco
        for linha in f:
            linha = linha.strip()
            if linha.startswith('>'):
                if header:
                    yield (header, sequencia)
                header = linha[1:]
                sequencia = ""
            else:
                sequencia += linha

        if header:
            yield (header, sequencia)

#Terceiro Bloco
for header, sequencia in ler_fasta(proteina):
      print(f">>{header}")
      print(f"Tamanho: {len(sequencia)}")
      print(f"Sequência: {sequencia[:30]}...")
      print()

from google.colab import drive
drive.mount('/content/drive')

dados = { i: (header, sequencia) for i, (header, sequencia) in enumerate(ler_fasta(proteina))}
print(dados)
seq = dados[15][1]
# [0] = nome
# [1] = sequencia
print(seq)

#Dicionário dos aminoácidos

pesos_aminoacidos = {
    "A": 89.09,   # Alanina
    "R": 174.20,  # Arginina
    "N": 132.12,  # Asparagina
    "D": 133.10,  # Ácido Aspártico
    "C": 121.16,  # Cisteína
    "Q": 146.15,  # Glutamina
    "E": 147.13,  # Ácido Glutâmico
    "G": 75.07,   # Glicina
    "H": 155.16,  # Histidina
    "I": 131.18,  # Isoleucina
    "L": 131.18,  # Leucina
    "K": 146.19,  # Lisina
    "M": 149.21,  # Metionina
    "F": 165.19,  # Fenilalanina
    "P": 115.13,  # Prolina
    "S": 105.09,  # Serina
    "T": 119.12,  # Treonina
    "W": 204.23,  # Triptofano
    "Y": 181.19,  # Tirosina
    "V": 117.15   # Valina
}
print(pesos_aminoacidos)

# Loop para contar cisteínas em cada sequência
for prot, (header, sequencia) in dados.items():

  quantas_cisteinas = sequencia.count("C")

  # Retornar resultado:
  print(f"\n{header}")
  print(f"Número de cisteínas: {quantas_cisteinas}")

  # Verificar se há ligações dissulfeto
  if quantas_cisteinas >= 2:
    print(f"Ligação dissulfeto? Sim")
  else:
    print(f"Ligação dissulfeto? Não")

  # Avaliar e printar quantas ligações dissulfeto podem ser formadas
  numero_de_ligacoes = quantas_cisteinas // 2
  print(f"Número de ligações: {numero_de_ligacoes}")

# Massa das proteínas

# Criar função chamada calcula_massa:

def calcula_massa(sequencia, peso):
    massa = sum(peso[p] for p in sequencia)
    perda = (len(seq) - 1) * 18.015  #peso da água
    return massa - perda

header, seq = dados[0]
massa = calcula_massa(seq, pesos_aminoacidos)
print(f"Proteína: {header} \n Massa: {massa:.2f} g/mol")

# Sítio de Glicosilação

# '''
# A lógica básica deve ser:
# caractere 1 == N
# caractere 2 != P
# caractere 3 == S or T
# '''

# for prot, (header, sequencia) in dados.items():
#   sitio_glicosilacao =



def verificar_sitio_glicosilacao(sequencia):
    sequencia = sequencia.upper()
    resultado = []

    for i in range(len(sequencia)- 2):
      if sequencia[i] == "N" and sequencia[i + 1] != "P" and sequencia[i + 2] in ["S","T"]:
        resultado.append((i, True, sequencia[i] + sequencia[i + 1] + sequencia[i + 2]))

      else:
        resultado.append((i, False, sequencia[i] + sequencia[i + 1] + sequencia[i + 2]))

    return resultado


x = "ASNGTRSH"
analise = verificar_sitio_glicosilacao(x)
print(analise)

# contar = sum(verificar_sitio_glicosilacao(x) for i in range(len(sequencia)))
# print(contar)

salva_true = {}

for item in analise:
    indice = item[0]
    flag = item[1]
    trio = item[2]

    if flag == True:
        salva_true[indice] = trio

print(salva_true)

!pip install gradio

import gradio as gr
import os

os.makedirs("uploads", exist_ok=True)

def save_file(file):
    filepath = os.path.join("uploads", file.name)
    with open(filepath, "wb") as f:
        f.write(file.read())
    return f"Arquivo salvo em: {filepath}"

app = gr.Interface(
    fn=save_file,
    inputs=gr.File(),
    outputs="text",
    title="Upload de Arquivo"
)

app.launch()

###DESIGN PATTERN

from abc import ABC,abstractmethod

####CLASSE ABSTRATA

class ProcessaProteina(ABC):

    def executar(self, arquivo_entrada, arquivo_saida):
        dados = self.ler(arquivo_entrada)
        resultados = self.processar(dados)
        self.salvar(resultados, arquivo_saida)

    @abstractmethod
    def ler(self, arquivo_entrada):
        pass

    @abstractmethod
    def processar(self, dados):
        pass

    @abstractmethod
    def salvar(self, resultados, arquivo_saida):
        pass


####CLASSE CONCRETA

class AnaliseProteina(ProcessaProteina):

  def ler(self, arquivo_entrada):

    def ler_fasta(arquivo):
      with open(arquivo, 'r') as f:
        header = ""
        sequencia = ""

        for linha in f:
            linha = linha.strip()
            if linha.startswith('>'):
                if header:
                    yield (header, sequencia)
                header = linha[1:]
                sequencia = ""
            else:
                sequencia += linha

        if header:
            yield (header, sequencia)


    dados = {i: (header, sequencia) for i, (h, s) in enumerate(ler_fasta(arquivo_entrada))}
    return dados


  def calcular_massa(self, sequencia):
        pesos = {
            "A": 89.09, "R": 174.20, "N": 132.12, "D": 133.10,
            "C": 121.16, "Q": 146.15, "E": 147.13, "G": 75.07,
            "H": 155.16, "I": 131.18, "L": 131.18, "K": 146.19,
            "M": 149.21, "F": 165.19, "P": 115.13, "S": 105.09,
            "T": 119.12, "W": 204.23, "Y": 181.19, "V": 117.15
        }

        massa_total = sum(pesos[aa] for aa in seq)
        perda = (len(seq) - 1) * 18.015
        return massa_total - perda


def conta_cisteinas(header, sequencia):

    quantas_cisteinas = sequencia.count("C")

    print(f"\n{header}")
    print(f"Número de cisteínas: {quantas_cisteinas}")

    # Verificar se há ligações dissulfeto
    if quantas_cisteinas >= 2:
        print("Ligação dissulfeto? Sim")
    else:
        print("Ligação dissulfeto? Não")

    # Quantas ligações dissulfeto podem ser formadas
    numero_de_ligacoes = quantas_cisteinas // 2
    print(f"Número de ligações: {numero_de_ligacoes}")

    # Retornar os valores caso você queira usar depois
    return quantas_cisteinas, numero_de_ligacoes


def verificar_sitio_glicosilacao(sequencia):
    sequencia = sequencia.upper()
    resultado = []

    for i in range(len(sequencia)- 2):
      if sequencia[i] == "N" and sequencia[i + 1] != "P" and sequencia[i + 2] in ["S","T"]:
        resultado.append((i, True, sequencia[i] + sequencia[i + 1] + sequencia[i + 2]))

      else:
        resultado.append((i, False, sequencia[i] + sequencia[i + 1] + sequencia[i + 2]))

    return resultado


salva_true = {}

for item in analise:
      indice = item[0]
      flag = item[1]
      trio = item[2]

      if flag == True:
          salva_true[indice] = trio



# ---------- PROCESSAR TODOS OS DADOS ----------
def processar(self, dados):

        resultados = []

        for _, (header, sequencia) in dados.items():

            massa = self.calcular_massa(sequencia)
            qtd_cis, diss, ligs = self.conta_cisteinas(sequencia)
            glico = self.verificar_glicosilacao(sequencia)

            resultados.append({
                "header": header,
                "tamanho": len(sequencia),
                "massa": massa,
                "cisteinas": qtd_cis,
                "dissulfeto": diss,
                "num_ligacoes": ligs,
                "glicosilacao": glico
            })

        return resultados

    # ---------- SALVAR EM CSV ----------#

def salvar(self, resultados, arquivo_saida):

        with open(arquivo_saida, "w") as f:

            f.write(
                "Header\tTamanho\tMassa(g/mol)\tCisteinas\tDissulfeto\tLigacoes\tGlicosilacao\n"
            )

            for r in resultados:
                linha = (
                    f"{r['header']}\t"
                    f"{r['tamanho']}\t"
                    f"{r['massa']:.2f}\t"
                    f"{r['cisteinas']}\t"
                    f"{r['dissulfeto']}\t"
                    f"{r['num_ligacoes']}\t"
                    f"{r['glicosilacao']}\n"
                )
                f.write(linha)

pipeline = AnaliseProteina()
pipeline.executar(proteina,"teste.csv")
