# -*- coding: utf-8 -*-
"""codigo_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5AgWD_WDsVtP63aj3ci7CYeADmRVps_
"""

### IMPORTS
from abc import ABC, abstractmethod
import gradio as gr
import os

### DESIGN PATTERN

#### CLASSE ABSTRATA

class ProcessaProteina(ABC):

    def executar(self, arquivo_entrada, arquivo_saida):
        dados = self.ler(arquivo_entrada)
        resultados = self.processar(dados)
        self.salvar(resultados, arquivo_saida)

    @abstractmethod
    def ler(self, arquivo_entrada):
        pass

    @abstractmethod
    def processar(self, dados):
        pass

    @abstractmethod
    def salvar(self, resultados, arquivo_saida):
        pass


#### CLASSE CONCRETA

class AnaliseProteina(ProcessaProteina):

    def ler(self, arquivo_entrada):

        def ler_fasta(arquivo):
            with open(arquivo, 'r') as f:
                header = ""
                sequencia = ""

                for linha in f:
                    linha = linha.strip()
                    if linha.startswith('>'):
                        if header:
                            yield (header, sequencia)
                        header = linha[1:]
                        sequencia = ""
                    else:
                        sequencia += linha

                if header:
                    yield (header, sequencia)

        dados = {i: (header, sequencia) for i, (header, sequencia) in enumerate(ler_fasta(arquivo_entrada))}
        return dados

    def calcular_massa(self, sequencia):
        pesos = {
            "A": 89.09, "R": 174.20, "N": 132.12, "D": 133.10,
            "C": 121.16, "Q": 146.15, "E": 147.13, "G": 75.07,
            "H": 155.16, "I": 131.18, "L": 131.18, "K": 146.19,
            "M": 149.21, "F": 165.19, "P": 115.13, "S": 105.09,
            "T": 119.12, "W": 204.23, "Y": 181.19, "V": 117.15
        }

        massa_total = sum(pesos[aa] for aa in sequencia if aa in pesos)
        perda = (len(sequencia) - 1) * 18.015
        return (massa_total - perda)/1000

    def conta_cisteinas(self, header, sequencia):
        quantas_cisteinas = sequencia.count("C")

        dissulfeto = "Sim" if quantas_cisteinas >= 2 else "Nao"

        numero_de_ligacoes = quantas_cisteinas // 2

        return header, quantas_cisteinas, dissulfeto, numero_de_ligacoes

    def verificar_glicosilacao(self, header, sequencia):
        sequencia = sequencia.upper()
        resultado = []

        for i in range(len(sequencia) - 2):
            trio = sequencia[i] + sequencia[i+1] + sequencia[i+2]

            if sequencia[i] == "N" and sequencia[i+1] != "P" and sequencia[i+2] in ["S", "T"]:
                resultado.append((i, trio))

        if len(resultado) == 0:
            return header, "Nao", None

        return header, "Sim", resultado

    # ---------- PROCESSAR TODOS OS DADOS ----------
    def processar(self, dados):
        resultados = []

        for _, (header, sequencia) in dados.items():
            massa = self.calcular_massa(sequencia)


            header_cis, qtd_cis, diss, ligs = self.conta_cisteinas(header, sequencia)
            header_glico, tem_glico, trincas = self.verificar_glicosilacao(header, sequencia)

            resultados.append({
                "header": header,
                "tamanho": len(sequencia),
                "massa": massa,
                "cisteinas": qtd_cis,
                "dissulfeto": diss,
                "num_ligacoes": ligs,
                "glicosilacao": tem_glico,
                "trincas_glico": trincas
            })

        return resultados

    # ---------- SALVAR EM CSV ----------
    def salvar(self, resultados, arquivo_saida):

        with open(arquivo_saida, "w") as f:


            f.write(
                "Header;Tamanho;Massa;Cisteinas;Dissulfeto;Ligacoes;Glicosilacao;Trincas\n"
            )


            for r in resultados:

                if r["trincas_glico"] is None:
                    trincas_formatadas = ""
                else:
                    trincas_formatadas = ",".join(f"{i}:{t}" for i, t in r["trincas_glico"])

                linha = (
                    f"{r['header']};"
                    f"{r['tamanho']};"
                    f"{r['massa']:.2f};"
                    f"{r['cisteinas']};"
                    f"{r['dissulfeto']};"
                    f"{r['num_ligacoes']};"
                    f"{r['glicosilacao']};"
                    f"{trincas_formatadas}\n"
                )


                f.write(linha)

def processar_pipeline(file_obj):
    if file_obj is None:
        return None

    proteina_path = file_obj.name

    nome_arquivo_completo = os.path.basename(proteina_path)
    nome_sem_extensao = os.path.splitext(nome_arquivo_completo)[0]

    novo_nome_csv = f"{nome_sem_extensao}_analisado.csv"

    caminho_saida_final = os.path.join("/content", novo_nome_csv)

    print(f"Lendo: {proteina_path}")
    print(f"Salvando em: {caminho_saida_final}")

    # CHAMANDO AS ANALISES
    pipeline = AnaliseProteina()
    pipeline.executar(proteina_path, caminho_saida_final)

    return caminho_saida_final


meu_tema = gr.themes.Soft(
    primary_hue="blue",
    secondary_hue="neutral",
)

descricao_texto = """
**Instruções:**

1. Faça upload de um arquivo `.fasta` contendo sequências de proteínas.
2. O sistema vai devolver um arquivo com as seguintes análises:
   - Massa molecular
   - Quantidade de cisteínas
   - Sítios de glicosilação
3. Faça o download.
"""

nota_rodape = """ Desenvolvido por Dávila Pacheco e Mariani Predolim"""

app = gr.Interface(
    fn=processar_pipeline,

    # Input
    inputs=gr.File(
        label="📂 Arquivo de Entrada",
        file_types=[".fasta"],
        file_count="single"
    ),

    # Output
    outputs=gr.File(label="⬇️ Baixar Relatório (.csv)"),

    title="🧬 Análises de Proteínas",
    description=descricao_texto,
    article=nota_rodape,

    theme=meu_tema,

)

app.launch()